<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_paket_model extends CI_Model
{

    public $table = 'jenis_paket';
    public $id = 'id_jenis_paket';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_jenis_paket,jenis_paket,gambar,tanggal');
        $this->datatables->from('jenis_paket');
        //add this line for join
        //$this->datatables->join('table2', 'jenis_paket.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jenis_paket/read/$1'),'Read')." | ".anchor(site_url('jenis_paket/update/$1'),'Update')." | ".anchor(site_url('jenis_paket/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_jenis_paket');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jenis_paket', $q);
  $this->db->or_like('jenis_paket', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jenis_paket', $q);
	$this->db->or_like('jenis_paket', $q);
  $this->db->or_like('gambar', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function buat_kode()   {
          $this->db->select('RIGHT(jenis_paket.id_jenis_paket, 2) as kode', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row();
           $kode = intval($data->kode) + 1;
          }
          else {
           //jika kode belum ada
           $kode = 1;
          }
          $kodemax = str_pad($kode, 4, "0", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
          $kodejadi = "JPK".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

}

/* End of file Jenis_paket_model.php */
/* Location: ./application/models/Jenis_paket_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-27 06:24:01 */
/* http://harviacode.com */